create database tarea2_eje5;
use tarea2_eje5;
create table cliente(codigo_cliente int, nombre varchar(50), apellidos varchar(50), nif int, telefono varchar(10), email varchar(30), fecha_alta date, numero_tarjeta int);
create table pedido(codigo_pedido int, numero_localizador int, importe_total float, fecha date, hora time, codigo_cliente int);
create table lineas_pedido(codigo_pedido int, numero_referencia int, importe_linea float);
create table articulo(numero_referencia int, nombre varchar(50), descripcion varchar(100), pvp int, cantidad int);
create table almacena(stock int, codigo_almacen int, numero_referencia int);
create table almacen(codigo_almacen int, nombre varchar(50), fecha_apertura date, direccion varchar(50), telefono varchar(10), gerente varchar(50), codigo_provincia int);
create table provincia(codigo_provincia int, nombre varchar(50), numero_habitantes int);
create table premium(codigo_premium int, descuento float, fecha_premium date, codigo_cliente int);
